name: Release-Please

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write
    issues: write
    packages: write

jobs:
    release-please:
        runs-on: ubuntu-latest

        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}

        steps:
            - uses: GoogleCloudPlatform/release-please-action@v4
              id: release
              with:
                  release-type: simple

            - name: Checkout source
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              run: |
                if [[ "${{ steps.release.outputs.release_created }}" == "true" ]]; then
                # For release-based builds
                echo "tag=${{ steps.release.outputs.tag_name }}" >> "$GITHUB_OUTPUT"
                echo "use_latest=true" >> "$GITHUB_OUTPUT"
                else
                # For main branch push with no release
                echo "tag=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
                echo "use_latest=false" >> "$GITHUB_OUTPUT"
                fi
                echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

            - name: Build and push with tag and latest
              if: steps.meta.outputs.use_latest == 'true'
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                platforms: linux/amd64
                push: true
                tags: |
                  ghcr.io/${{ steps.meta.outputs.owner_lc }}/${{ github.event.repository.name }}:${{ steps.meta.outputs.tag }}
                  ghcr.io/${{ steps.meta.outputs.owner_lc }}/${{ github.event.repository.name }}:latest

            - name: Build and push with commit ID
              if: steps.meta.outputs.use_latest == 'false'
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                platforms: linux/amd64
                push: true
                tags: |
                  ghcr.io/${{ steps.meta.outputs.owner_lc }}/${{ github.event.repository.name }}:${{ steps.meta.outputs.tag }}
