name: Release-Please

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write
    issues: write
    packages: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
            tag_name: ${{ steps.release.outputs.tag_name }}

        steps:
            - uses: GoogleCloudPlatform/release-please-action@v4
              id: release
              with:
                  release-type: simple

    build-docker:
        needs: release-please
        runs-on: ubuntu-latest
        if: ${{ needs.release-please.outputs.release_created == 'true' }}

        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}-docker

        steps:
            - name: Checkout source
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              env:
                  OWNER: ${{ github.repository_owner }}
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: linux/amd64
                  push: true
                  tags: |
                      ghcr.io/${{ env.OWNER }}/${{ github.event.repository.name }}:${{ needs.release-please.outputs.tag_name }}
                      ghcr.io/${{ env.OWNER }}/${{ github.event.repository.name }}:latest

    run-pipeline:
        needs: [release-please, build-docker]
        runs-on: ubuntu-latest
        if: ${{ needs.release-please.outputs.release_created == 'true' }}
        
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}-pipeline
            
        steps:
            - name: Checkout source
              uses: actions/checkout@v4
              with:
                  ref: ${{ needs.release-please.outputs.tag_name }}
              
            - name: Run PharmacoSet Pipeline
              uses: ./.github/actions/run-pipeline
              with:
                artifact-name: CTRP-TreatmentResponseExperiment
                result-path: data/results/CTRPv2.0_treatmentResponseExperiment.RDS
                release-tag: ${{ needs.release-please.outputs.tag_name }}
